export const userComment = [
  { dummy: '' },
  { dummy: '' },
  { dummy: '' },
  { dummy: '' },
  { dummy: '' },
  { dummy: '' },
  { dummy: '' },
  { dummy: '' },
  { dummy: '' },
  { dummy: '' },
  { dummy: '' },
  { dummy: '' },
  { dummy: '' },
  { dummy: '' },
  { dummy: '' },
  { dummy: '' },
  { dummy: '' },
  { dummy: '' },
  { dummy: '' },
  { dummy: '' },
]
